[platformio]
default_envs = esp32-wrover-ie-n16r8
boards_dir = boards

[env:esp32-wrover-ie-n16r8]
platform = espressif32
board = esp32-wrover-ie-n16r8
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

lib_deps =
  https://github.com/pschatzmann/arduino-audio-tools.git
  https://github.com/pschatzmann/arduino-snapclient.git
  https://github.com/pschatzmann/arduino-libopus.git
  https://github.com/pschatzmann/ESP32-A2DP.git

lib_ldf_mode = deep+

build_type = release
board_build.partitions = default_16MB.csv

build_flags =
  -O2
  -DCORE_DEBUG_LEVEL=3
  -DCONFIG_SNAPCLIENT_USE_MDNS=false
  -DCONFIG_NVS_FLASH=false
