[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  https://github.com/pschatzmann/arduino-audio-tools.git
  https://github.com/pschatzmann/arduino-snapclient.git
  https://github.com/pschatzmann/codec-opus.git

lib_ldf_mode = deep+

build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DCONFIG_SNAPCLIENT_USE_MDNS=false
  -DCONFIG_NVS_FLASH=false